// resources/js/pages/DashboardPage.vue
<template>
    <div class="min-h-screen bg-gray-50 flex">
        <!-- Sidebar -->
        <div class="w-64 bg-white shadow-lg border-r border-gray-200">
            <!-- Logo -->
            <div class="p-6 border-b border-gray-200">
                <div class="flex items-center">
                    <div class="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center mr-3">
                        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                        </svg>
                    </div>
                    <h1 class="text-xl font-bold text-gray-900">Micro Tracker</h1>
                </div>
            </div>

            <!-- Navigation -->
            <nav class="mt-12">
                <div class="px-6 space-y-3">
                    <button
                        v-for="tab in tabs"
                        :key="tab.id"
                        @click="activeTab = tab.id"
                        :class="[
                            activeTab === tab.id
                                ? 'bg-blue-50 border-r-4 border-blue-500 text-blue-700 font-semibold'
                                : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900',
                            'group flex items-center px-6 py-4 text-sm font-medium rounded-l-lg transition-all duration-200 w-full text-left'
                        ]"
                    >
                        <component :is="tab.icon" class="mr-4 h-5 w-5 flex-shrink-0" />
                        <span class="truncate">{{ tab.name }}</span>
                        <div v-if="activeTab === tab.id" class="ml-auto">
                            <div class="w-2 h-2 bg-blue-500 rounded-full"></div>
                        </div>
                    </button>
                </div>
            </nav>
        </div>

        <!-- Main Content -->
        <div class="flex-1 flex flex-col">
            <!-- Top Bar -->
            <header class="bg-white shadow-sm border-b border-gray-200">
                <div class="px-6 py-5">
                    <div class="flex items-center justify-between">
                        <div class="flex items-center space-x-6">
                            <div>
                                <h2 class="text-2xl font-bold text-gray-900">{{ getCurrentTabName() }}</h2>
                                <p class="text-sm text-gray-500 mt-1">Manage your analytics and tracking data</p>
                            </div>
                            <!-- Project Switcher -->
                            <div v-if="projectStore.activeProject" class="flex items-center space-x-3">
                                <div class="flex items-center space-x-2">
                                    <label class="text-sm font-medium text-gray-700">Project:</label>
                                    <select 
                                        v-model="projectStore.activeProjectId" 
                                        @change="handleProjectChange"
                                        class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                                    >
                                        <option 
                                            v-for="project in projectStore.projects" 
                                            :key="project.id" 
                                            :value="project.id"
                                        >
                                            {{ project.name }}
                                        </option>
                                    </select>
                                </div>
                                <button
                                    @click="showCreateProjectModal = true"
                                    class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200 flex items-center space-x-2"
                                >
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                                    </svg>
                                    <span>Create Project</span>
                                </button>
                            </div>
                        </div>
                        <div class="flex items-center space-x-4">
                            <div class="text-right">
                                <p class="text-sm font-medium text-gray-900">{{ authStore.user?.name }}</p>
                                <p class="text-xs text-gray-500">Welcome back</p>
                            </div>
                            <button
                                @click="handleLogout"
                                class="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors duration-200"
                                title="Logout"
                            >
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Page Content -->
            <main class="flex-1 bg-gray-50 p-8">
                <div v-if="projectStore.loading" class="text-center py-12">
                    <div class="animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600 mx-auto"></div>
                    <p class="mt-4 text-gray-600">Loading your dashboard...</p>
                </div>
                
                <div v-else-if="!projectStore.activeProject" class="text-center py-12">
                    <div class="bg-white shadow-sm rounded-lg border border-gray-200 p-8 max-w-md mx-auto">
                        <div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                            <svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                            </svg>
                        </div>
                        <h2 class="text-2xl font-bold text-gray-900 mb-2">No Project Selected</h2>
                        <p class="text-gray-600 mb-6">Create your first project to start tracking analytics and gaining insights.</p>
                        <button
                            @click="showCreateProjectModal = true"
                            class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium transition-colors duration-200 flex items-center space-x-2 mx-auto"
                        >
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
                            </svg>
                            <span>Create Your First Project</span>
                        </button>
                    </div>
                </div>
                
                <div v-else class="space-y-6">
                    <!-- Visitors Tab -->
                    <div v-if="activeTab === 'visitors'">
                        <VisitorsTab />
                    </div>

                    <!-- Sessions Tab -->
                    <div v-else-if="activeTab === 'sessions'">
                        <SessionsTab />
                    </div>

                    <!-- Events Tab -->
                    <div v-else-if="activeTab === 'events'">
                        <EventsTab />
                    </div>

                    <!-- Settings Tab -->
                    <div v-else-if="activeTab === 'settings'">
                        <SettingsTab />
                    </div>
                </div>
            </main>
        </div>

        <!-- Create Project Modal -->
        <CreateProjectModal 
            v-if="showCreateProjectModal"
            @close="showCreateProjectModal = false"
            @created="handleProjectCreated"
        />
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';
import { useProjectStore } from '../stores/project';
import VisitorsTab from '../components/dashboard/VisitorsTab.vue';
import SessionsTab from '../components/dashboard/SessionsTab.vue';
import EventsTab from '../components/dashboard/EventsTab.vue';
import SettingsTab from '../components/dashboard/SettingsTab.vue';
import CreateProjectModal from '../components/CreateProjectModal.vue';

const router = useRouter();
const authStore = useAuthStore();
const projectStore = useProjectStore();

const activeTab = ref('visitors');
const showCreateProjectModal = ref(false);

// Icon components
const VisitorsIcon = {
    template: `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m13.5-9a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"></path>
    </svg>`
};

const SessionsIcon = {
    template: `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
    </svg>`
};

const EventsIcon = {
    template: `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
    </svg>`
};

const SettingsIcon = {
    template: `<svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
    </svg>`
};

const tabs = [
    { id: 'visitors', name: 'Visitors', icon: VisitorsIcon },
    { id: 'sessions', name: 'Sessions', icon: SessionsIcon },
    { id: 'events', name: 'Events', icon: EventsIcon },
    { id: 'settings', name: 'Settings', icon: SettingsIcon }
];

onMounted(async () => {
    await projectStore.initialize();
});

const handleLogout = async () => {
    await authStore.logout();
    router.push('/');
};

const handleProjectChange = () => {
    if (projectStore.activeProjectId) {
        projectStore.setActiveProject(projectStore.activeProjectId);
    }
};

const handleProjectCreated = () => {
    showCreateProjectModal.value = false;
    projectStore.loadProjects();
};

const getCurrentTabName = () => {
    const currentTab = tabs.find(tab => tab.id === activeTab.value);
    return currentTab ? currentTab.name : 'Dashboard';
};
</script>

// resources/js/pages/DashboardPage.tsx
import { useState } from 'react';
import { Routes, Route, Link, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useProject } from '../contexts/ProjectContext';
import { ProjectSwitcher } from '../components/ProjectSwitcher';
import { 
    BarChart3, 
    Users, 
    Activity, 
    Calendar, 
    Target, 
    DollarSign, 
    Settings,
    LogOut,
    Menu,
    X
} from 'lucide-react';

// Import tab components (we'll create these)
import VisitorsTab from '../components/dashboard/VisitorsTab';
import SessionsTab from '../components/dashboard/SessionsTab';
import EventsTab from '../components/dashboard/EventsTab';
import AdsTab from '../components/dashboard/AdsTab';
import SpendTab from '../components/dashboard/SpendTab';
import AnalyticsTab from '../components/dashboard/AnalyticsTab';
import SettingsTab from '../components/dashboard/SettingsTab';

const tabs = [
    { id: 'visitors', name: 'Visitors', icon: Users, path: '/visitors' },
    { id: 'sessions', name: 'Sessions', icon: Activity, path: '/sessions' },
    { id: 'events', name: 'Events', icon: Calendar, path: '/events' },
    { id: 'ads', name: 'Ads', icon: Target, path: '/ads' },
    { id: 'spend', name: 'Spend', icon: DollarSign, path: '/spend' },
    { id: 'analytics', name: 'Analytics', icon: BarChart3, path: '/analytics' },
    { id: 'settings', name: 'Settings', icon: Settings, path: '/settings' },
];

export default function DashboardPage() {
    const { user, logout } = useAuth();
    const { activeProject, isLoading: projectLoading } = useProject();
    const location = useLocation();
    const [sidebarOpen, setSidebarOpen] = useState(false);

    const handleLogout = async () => {
        await logout();
    };

    const currentTab = tabs.find(tab => location.pathname.includes(tab.path)) || tabs[0];

    // Show loading state while projects are loading
    if (projectLoading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-blue-600"></div>
            </div>
        );
    }

    // Show project selection prompt if no active project
    if (!activeProject) {
        return (
            <div className="min-h-screen flex items-center justify-center bg-gray-50">
                <div className="text-center">
                    <h2 className="text-2xl font-bold text-gray-900 mb-4">No Project Selected</h2>
                    <p className="text-gray-600 mb-6">Please create or select a project to continue.</p>
                    <ProjectSwitcher />
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-50">
            {/* Mobile sidebar */}
            <div className={`fixed inset-0 z-50 lg:hidden ${sidebarOpen ? 'block' : 'hidden'}`}>
                <div className="fixed inset-0 bg-gray-600 bg-opacity-75" onClick={() => setSidebarOpen(false)} />
                <div className="relative flex-1 flex flex-col max-w-xs w-full bg-white">
                    <div className="absolute top-0 right-0 -mr-12 pt-2">
                        <button
                            type="button"
                            className="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                            onClick={() => setSidebarOpen(false)}
                        >
                            <X className="h-6 w-6 text-white" />
                        </button>
                    </div>
                    <SidebarContent currentTab={currentTab} onLogout={handleLogout} />
                </div>
            </div>

            {/* Top bar - moved to top of screen */}
            <div className="sticky top-0 z-10 flex-shrink-0 flex h-16 bg-white shadow">
                <button
                    type="button"
                    className="px-4 border-r border-gray-200 text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500 lg:hidden"
                    onClick={() => setSidebarOpen(true)}
                >
                    <Menu className="h-6 w-6" />
                </button>
                <div className="flex-1 px-4 flex justify-between">
                    <div className="flex-1 flex items-center space-x-4">
                        <h1 className="text-2xl font-semibold text-gray-900">
                            {currentTab.name}
                        </h1>
                        <ProjectSwitcher />
                    </div>
                    <div className="ml-4 flex items-center md:ml-6">
                        <div className="flex items-center space-x-4">
                            <span className="text-sm text-gray-700">Welcome, {user?.name}</span>
                            <button
                                onClick={handleLogout}
                                className="bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                            >
                                <LogOut className="h-6 w-6" />
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div className="flex">
                {/* Desktop sidebar */}
                <div className="hidden lg:flex lg:flex-shrink-0">
                    <div className="flex flex-col w-64">
                        <SidebarContent currentTab={currentTab} onLogout={handleLogout} />
                    </div>
                </div>

                {/* Main content */}
                <div className="flex flex-col flex-1">
                    {/* Page content */}
                    <main className="flex-1">
                        <div className="py-6">
                            <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
                                <Routes>
                                    <Route path="/" element={<VisitorsTab />} />
                                    <Route path="/visitors" element={<VisitorsTab />} />
                                    <Route path="/sessions" element={<SessionsTab />} />
                                    <Route path="/events" element={<EventsTab />} />
                                    <Route path="/ads" element={<AdsTab />} />
                                    <Route path="/spend" element={<SpendTab />} />
                                    <Route path="/analytics" element={<AnalyticsTab />} />
                                    <Route path="/settings" element={<SettingsTab />} />
                                </Routes>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        </div>
    );
}

function SidebarContent({ currentTab, onLogout }: { currentTab: any, onLogout: () => void }) {
    return (
        <div className="flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-white">
            <div className="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
                <div className="flex items-center flex-shrink-0 px-4">
                    <BarChart3 className="h-8 w-8 text-blue-600" />
                    <span className="ml-2 text-xl font-bold text-gray-900">Micro Tracker</span>
                </div>
                <nav className="mt-5 flex-1 px-2 space-y-1">
                    {tabs.map((tab) => {
                        const Icon = tab.icon;
                        const isActive = currentTab.id === tab.id;
                        return (
                            <Link
                                key={tab.id}
                                to={`/app${tab.path}`}
                                className={`group flex items-center px-2 py-2 text-sm font-medium rounded-md ${
                                    isActive
                                        ? 'bg-blue-100 text-blue-900'
                                        : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                                }`}
                            >
                                <Icon
                                    className={`mr-3 flex-shrink-0 h-6 w-6 ${
                                        isActive ? 'text-blue-500' : 'text-gray-400 group-hover:text-gray-500'
                                    }`}
                                />
                                {tab.name}
                            </Link>
                        );
                    })}
                </nav>
            </div>
            <div className="flex-shrink-0 flex border-t border-gray-200 p-4">
                <button
                    onClick={onLogout}
                    className="flex-shrink-0 w-full group block"
                >
                    <div className="flex items-center">
                        <div>
                            <LogOut className="inline-block h-6 w-6 text-gray-400 group-hover:text-gray-500" />
                        </div>
                        <div className="ml-3">
                            <p className="text-sm font-medium text-gray-700 group-hover:text-gray-900">
                                Sign out
                            </p>
                        </div>
                    </div>
                </button>
            </div>
        </div>
    );
}
