// resources/js/pages/LandingPage.tsx
import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, Target, Zap } from 'lucide-react';

export default function LandingPage() {
    return (
        <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
            {/* Header */}
            <header className="px-4 lg:px-6 h-16 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                    <BarChart3 className="h-8 w-8 text-blue-600" />
                    <span className="text-xl font-bold text-gray-900">Micro Tracker</span>
                </div>
                <nav className="flex items-center space-x-4">
                    <Link
                        to="/login"
                        className="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
                    >
                        Sign In
                    </Link>
                    <Link
                        to="/signup"
                        className="bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-700"
                    >
                        Get Started
                    </Link>
                </nav>
            </header>

            {/* Hero Section */}
            <main className="px-4 lg:px-6 py-12">
                <div className="max-w-7xl mx-auto">
                    <div className="text-center">
                        <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
                            Track What Matters
                            <span className="block text-blue-600">Measure Everything</span>
                        </h1>
                        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
                            The ultimate micro-tracking platform for modern businesses. 
                            Get insights into user behavior, ad performance, and conversion metrics.
                        </p>
                        <div className="flex flex-col sm:flex-row gap-4 justify-center">
                            <Link
                                to="/signup"
                                className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-medium hover:bg-blue-700 flex items-center justify-center"
                            >
                                Start Free Trial
                                <ArrowRight className="ml-2 h-5 w-5" />
                            </Link>
                            <Link
                                to="/login"
                                className="border border-gray-300 text-gray-700 px-8 py-3 rounded-lg text-lg font-medium hover:bg-gray-50"
                            >
                                Sign In
                            </Link>
                        </div>
                    </div>

                    {/* Features */}
                    <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
                        <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                                <Target className="h-6 w-6 text-blue-600" />
                            </div>
                            <h3 className="text-xl font-semibold text-gray-900 mb-2">CPEV Tracking</h3>
                            <p className="text-gray-600">
                                Track Cost Per Engaged Visitor with precision. Understand which ads drive real engagement.
                            </p>
                        </div>

                        <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                            <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                                <BarChart3 className="h-6 w-6 text-green-600" />
                            </div>
                            <h3 className="text-xl font-semibold text-gray-900 mb-2">Scroll Velocity</h3>
                            <p className="text-gray-600">
                                Measure how users interact with your content through advanced scroll tracking.
                            </p>
                        </div>

                        <div className="text-center p-6 bg-white rounded-lg shadow-sm">
                            <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                                <Zap className="h-6 w-6 text-purple-600" />
                            </div>
                            <h3 className="text-xl font-semibold text-gray-900 mb-2">PCQS Scoring</h3>
                            <p className="text-gray-600">
                                Advanced Page Content Quality Score to measure content engagement effectiveness.
                            </p>
                        </div>
                    </div>

                    {/* CTA Section */}
                    <div className="mt-20 text-center">
                        <h2 className="text-3xl font-bold text-gray-900 mb-4">
                            Ready to Get Started?
                        </h2>
                        <p className="text-xl text-gray-600 mb-8">
                            Join thousands of businesses already tracking with Micro Tracker.
                        </p>
                        <Link
                            to="/signup"
                            className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-medium hover:bg-blue-700 inline-flex items-center"
                        >
                            Create Your Account
                            <ArrowRight className="ml-2 h-5 w-5" />
                        </Link>
                    </div>
                </div>
            </main>

            {/* Footer */}
            <footer className="mt-20 border-t border-gray-200">
                <div className="max-w-7xl mx-auto px-4 lg:px-6 py-8">
                    <div className="text-center text-gray-600">
                        <p>&copy; 2024 Micro Tracker. All rights reserved.</p>
                    </div>
                </div>
            </footer>
        </div>
    );
}

// resources/js/pages/LandingPage.vue
<template>
    <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
        <!-- Navigation -->
        <nav class="bg-white/80 backdrop-blur-sm shadow-sm">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex justify-between h-16">
                    <div class="flex items-center">
                        <div class="flex-shrink-0">
                            <h1 class="text-2xl font-bold text-gray-900">Micro Tracker</h1>
                        </div>
                    </div>
                    <div class="flex items-center space-x-4">
                        <router-link
                            to="/login"
                            class="text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium"
                        >
                            Sign In
                        </router-link>
                        <router-link
                            to="/signup"
                            class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium"
                        >
                            Get Started
                        </router-link>
                    </div>
                </div>
            </div>
        </nav>

        <!-- Hero Section -->
        <div class="relative">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
                <div class="text-center">
                    <h1 class="text-5xl font-bold text-gray-900 sm:text-6xl md:text-7xl">
                        Track Everything
                        <span class="text-blue-600">Simply</span>
                    </h1>
                    <p class="mt-6 max-w-3xl mx-auto text-xl text-gray-600">
                        Micro Tracker is the simplest way to add powerful analytics to your web applications. 
                        Track visitors, events, and user behavior with just a few lines of code.
                    </p>
                    <div class="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
                        <router-link
                            to="/signup"
                            class="inline-flex items-center px-8 py-4 border border-transparent text-lg font-medium rounded-lg text-white bg-blue-600 hover:bg-blue-700 transition-colors duration-200"
                        >
                            Start Tracking Free
                        </router-link>
                        <router-link
                            to="/login"
                            class="inline-flex items-center px-8 py-4 border border-gray-300 text-lg font-medium rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-colors duration-200"
                        >
                            Sign In
                        </router-link>
                    </div>
                </div>
            </div>
        </div>

        <!-- Features Section -->
        <div class="bg-white py-20">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="text-center">
                    <h2 class="text-3xl font-bold text-gray-900 sm:text-4xl">
                        Everything you need to understand your users
                    </h2>
                    <p class="mt-4 text-lg text-gray-600">
                        Powerful analytics made simple
                    </p>
                </div>

                <div class="mt-16 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
                    <div class="bg-gray-50 p-6 rounded-lg">
                        <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                            <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                            </svg>
                        </div>
                        <h3 class="mt-4 text-lg font-semibold text-gray-900">Real-time Analytics</h3>
                        <p class="mt-2 text-gray-600">
                            See visitor behavior and events as they happen with real-time tracking and reporting.
                        </p>
                    </div>

                    <div class="bg-gray-50 p-6 rounded-lg">
                        <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center">
                            <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                            </svg>
                        </div>
                        <h3 class="mt-4 text-lg font-semibold text-gray-900">Lightning Fast</h3>
                        <p class="mt-2 text-gray-600">
                            Minimal impact on your site's performance with our lightweight tracking script.
                        </p>
                    </div>

                    <div class="bg-gray-50 p-6 rounded-lg">
                        <div class="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center">
                            <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path>
                            </svg>
                        </div>
                        <h3 class="mt-4 text-lg font-semibold text-gray-900">Privacy First</h3>
                        <p class="mt-2 text-gray-600">
                            Your data stays yours. We don't sell or share your analytics data with third parties.
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- CTA Section -->
        <div class="bg-blue-600">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                <div class="text-center">
                    <h2 class="text-3xl font-bold text-white sm:text-4xl">
                        Ready to start tracking?
                    </h2>
                    <p class="mt-4 text-xl text-blue-100">
                        Join thousands of developers who trust Micro Tracker for their analytics needs.
                    </p>
                    <div class="mt-8">
                        <router-link
                            to="/signup"
                            class="inline-flex items-center px-8 py-4 border border-transparent text-lg font-medium rounded-lg text-blue-600 bg-white hover:bg-gray-50 transition-colors duration-200"
                        >
                            Get Started Free
                        </router-link>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer -->
        <footer class="bg-gray-900">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div class="text-center">
                    <h3 class="text-2xl font-bold text-white">Micro Tracker</h3>
                    <p class="mt-4 text-gray-400">
                        Simple, powerful analytics for modern web applications.
                    </p>
                    <p class="mt-8 text-gray-500 text-sm">
                        © 2024 Micro Tracker. All rights reserved.
                    </p>
                </div>
            </div>
        </footer>
    </div>
</template>

<script setup lang="ts">
// Landing page component
</script>
